# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'IT Infra-46(23a10725-0f45-4b82-88e0-189c6e8c94a9)'
    subscriptionId: '23a10725-0f45-4b82-88e0-189c6e8c94a9'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'esha7000'
    location: 'East US 2'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/kapoorisha221/ARMPipeline-repo/main/create_web_app/azuredeploy.json'
    overrideParameters: '-projectName myarm'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'
